export const RANDOM_SWAPI_PENDING = 'RANDOM_SWAPI_PENDING';
export const RANDOM_SWAPI_SUCCESS = 'RANDOM_SWAPI_SUCCESS';
export const RANDOM_SWAPI_FAILED = 'RANDOM_SWAPI_FAILED';
export const SEARCH_SWAPI_PENDING = 'SEARCH_SWAPI_PENDING';
export const SEARCH_SWAPI_SUCCESS = 'SEARCH_SWAPI_SUCCESS';
export const SEARCH_SWAPI_FAILED = 'SEARCH_SWAPI_FAILED';
